### ISSUE TITLE
PIP INSTALL NOT UP TO DATE

### ISSUE THREAD

**Issue by MrAch26** [TrangPham/django-admin-confirm#4] opened 2021-01-20 21:37 UTC
Hi
after trying yours package using pip install django-admin-confirm I realized the Installation is not up to date,
![Screen Shot 2021-01-20 at 23 32 03](https://user-images.githubusercontent.com/62887460/105243401-b4f31f00-5b77-11eb-8849-2d99d350e52d.png)

it misses the templates and no error was appearing...

I had to clone this project and replace the 'admin_confirm' folder inside the site-package in order for it to work

I wouldn't want anyone to face the same issues but other than that the packages is really useful 

Thanks,

Daniel

**Comment by TrangPham** [comment] 2021-01-20 23:12
🤦 Thanks for opening the issue and the feedback :) 

I'm glad that you are enjoying the library so far. I'll update the package on pypi after fixing it

**Comment by ambareng** [comment] 2021-01-21 09:14
Hi, may I know what exactly you did to make it work. I also tried installing this through pip and it didn't work. Can you help?

**Comment by TrangPham** [comment] 2021-01-21 21:11
> Hi, may I know what exactly you did to make it work. I also tried installing this through pip and it didn't work. Can you help?

Hi ambareng, 

I am still figuring out how to fix the package. But for now you can clone this project, and copy the contents of `admin_confirm` folder to where you have the installed folder. This is usually `../site-packages/admin_confirm`. In my case I have it installed as such:

```
> ls /Users/thu/.pyenv/versions/3.8.0/lib/python3.8/site-packages | grep admin_confirm
admin_confirm
django_admin_confirm-0.2.dist-info
```

The issue is that the package is missing the templates and css folder.

**Comment by TrangPham** [comment] 2021-01-21 21:36
Thanks all for your patience with this project. This is my first self-published open source package, so I am still learning ^^

Here's the info I found helpful in solving this issue:
https://python-packaging.readthedocs.io/en/latest/non-code-files.html
https://packaging.python.org/guides/using-manifest-in/

Output of `make package`:
```
adding 'admin_confirm/__init__.py'
adding 'admin_confirm/admin.py'
adding 'admin_confirm/utils.py'
adding 'admin_confirm/static/admin/css/confirmation.css'
adding 'admin_confirm/templates/admin/action_confirmation.html'
adding 'admin_confirm/templates/admin/change_confirmation.html'
adding 'admin_confirm/templates/admin/change_data.html'
adding 'admin_confirm/templates/admin/submit_line.html'
adding 'django_admin_confirm-0.2.1.dist-info/LICENSE'
adding 'django_admin_confirm-0.2.1.dist-info/METADATA'
adding 'django_admin_confirm-0.2.1.dist-info/WHEEL'
adding 'django_admin_confirm-0.2.1.dist-info/top_level.txt'
adding 'django_admin_confirm-0.2.1.dist-info/RECORD'
removing build/bdist.macosx-10.15-x86_64/wheel
```
We can see that the package should now include the template and css folders. 

I have tested the new release :) This is now fixed in version `0.2.1`, please let me know if there's any issues with it.

Thanks for using Django-admin-confirm :) It makes me happy that it's useful for others

**Closed** 2021-01-21 21:38 UTC
Labels: bug

**Comment by MrAch26** [comment] 2021-01-24 09:50
> Thanks for using Django-admin-confirm :) It makes me happy that it's useful for others

You're doing great @TrangPham, just for confirmation after trying ` pip install django-admin-confirm --upgrade ` it all seems to be working :) 

Can't wait for the next features and the V1 to be released 🥳

**Comment by TrangPham** [comment] 2021-01-24 19:25
Ahaha I don’t know why I started the versions at 0.1 

What features would you want to have? @MrAch26

**Comment by MrAch26** [comment] 2021-01-25 13:59
Haha, thanks for asking  :)
I am working on building a CMS (content management system) with the Django admin panel and I think these features could be helpful to have as well : 
'''
 add help tooltip/popover to any field for more info
 add help tooltop/popover/help button to admin actions on changelist
 run scripts from admin
'''
But all good no rush 👍
